### ISSUE TITLE
Cannot install pycurl with dockerizePip

### ISSUE THREAD

**Issue by pg1671** [UnitedIncome/serverless-python-requirements#255] opened 2018-09-30 22:47 UTC
Using the default dockerfile under python2.7 I get the following when trying to install pycurl:
Could not run curl-config: [Errno 2] No such file or directory

If I then use a custom dockerfile where I attempt to install libcurl-devel I get:
Error: The command '/bin/sh -c yum install -y libcurl-devel' returned a non-zero code: 1
(is there a different package I should install on the variant of linux used for the default base image)

If I then switch the base image to amazonlinux:1 as suggested on the main page it seems to work but when my lambda runs I get:
Unable to import module 'handle_update': pycurl: libcurl link-time version (7.51.0) is older than compile-time version (7.53.1)

Thanks

**Comment by dschep** [comment] 2018-10-01 17:57
hmm. Could your dockerfile install libcurl 7.51.0 specifically? That might do the trick. You're actually kinda lucky, this error implies that the curl `.so` files already exist in lambda, so you don't have to do the extra work (which this plugin doesn't do) of adding that to your package.

**Comment by miketheman** [comment] 2020-02-22 19:26
I've been unable to reproduce this issue with recent versions. Considering the age of this issue, I'm going to close it out. If this is still a problem, please open a new issue with details about what versions are being used, and the current error messages, along with any other relevant information that would assist with reproducing the issue.

**Closed by miketheman** 2020-02-22 19:26 UTC
Labels: cannot confirm
