### ISSUE TITLE
/var/task:z: No such file or directory

### ISSUE THREAD

**Issue by NakedKoala** [UnitedIncome/serverless-python-requirements#134] opened 2018-01-30 04:37 UTC
Hello, I am new to serveless

I am trying to follow this tutorial:
https://serverless.com/blog/serverless-python-packaging/

But I am not able to get the docker to run 

```
venv) ➜  numpy-test serverless deploy
Serverless: Installing required Python packages with python3.6...
Serverless: Docker Image: lambci/lambda:build-python3.6
 
  Error --------------------------------------------------
 
  /bin/sh: DS/numpy-test:/var/task:z: No such file or directory
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.3.0
     Serverless Version:     1.26.0


```

This is my serverless.yml file
```
service: numpy-test



plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux


provider:
  name: aws
  runtime: python3.6

functions:
  numpy:
    handler: handler.main
```

Any help is appreciated

**Comment by dschep** [comment] 2018-01-30 13:13
Hmm. What is the path of your project? I think the issue is that there's a space in it. If that's the case there's a bug with that apparently, for now move to a path without spaces.

**Comment by sweeneybw1** [comment] 2018-03-21 14:55
I've run into same exact problem, but just to level set I'm running Windows 7 and using Docker Toolbox(deprecated) but also no spaces in path or anything like that. For @ClouddH  here is a link that I came across that seems to at least move the conversation forward.

https://www.mydatahack.com/resolving-docker-deamon-is-not-running-error-from-command-prompt/

The key component is running in venv SET COMPOSE_CONVERT_WINDOWS_PATHS=true
or as I've seen it elsewhere 
SET COMPOSE_CONVERT_WINDOWS_PATHS=1

**Comment by sweeneybw1** [comment] 2018-03-21 19:26
![image](https://user-images.githubusercontent.com/6716905/37732619-f060212e-2d1b-11e8-8d73-3c42cc0fe7ea.png)

Attached is screenshot of error with the path used on my machine. I will take a look at the beta release shortly.

**Comment by dschep** [comment] 2018-03-21 23:57
Ah yes, from that error, the changes in v4 will definitely help. Let me know how it goes.

**Comment by bsamuel-ui** [comment] 2018-11-29 19:19
Closing as stale.

**Closed by bsamuel-ui** 2018-11-29 19:19 UTC
