### ISSUE TITLE
fileName override fails if pyproject.toml exists

### ISSUE THREAD

**Issue by daishi** [UnitedIncome/serverless-python-requirements#411] opened 2019-09-23 22:40 UTC
# Situation

- You override `fileName` as documented here: https://github.com/UnitedIncome/serverless-python-requirements#customize-requirements-file-name
- You have a `pyproject.toml` in your root to configure [Black](https://pypi.org/project/black/).
- You know nothing about Poetry.

# What happens

You end up with an error like
```
  Error: ENOENT: no such file or directory, open '.../.serverless/requirements.txt'
      at Object.fs.openSync (fs.js:646:18)
      at Object.fs.readFileSync (fs.js:551:33)
      at filterRequirementsFile (/home/daishi/src/p4p_backend/node_modules/serverless-python-requirements/lib/pip.js:355:6)
      at generateRequirementsFile (/home/daishi/src/p4p_backend/node_modules/serverless-python-requirements/lib/pip.js:67:5)
...
```

# Diagnosis

Tracing execution to https://github.com/UnitedIncome/serverless-python-requirements/blob/master/lib/pip.js#L65 shows that unless you explicitly set `usePoetry: false`, all of the `sls` commands will fail with the above error.

**Comment by zygopleural** [comment] 2019-11-29 10:56
Also seeing this error

**Comment by aspin** [comment] 2019-12-09 23:02
+1, but this happens even when I don't customize the requirements file name

**Comment by levakin** [comment] 2019-12-26 10:58
+1

**Comment by bsamuel-ui** [comment] 2020-02-19 16:36
Duplicate of #400 .

**Closed by bsamuel-ui** 2020-02-19 16:36 UTC
Labels: bug
