### ISSUE TITLE
Feature request: use Lambda Layers for python packages

### ISSUE THREAD

**Issue by str3tch** [UnitedIncome/serverless-python-requirements#299] opened 2018-12-05 06:37 UTC
I am flat out and have no time to do this, so I'll write it here in case someone else does - or at least start a conversation about it.

Now that Lambda has the concept of Layers, it would be great if we can utilise them for common python dependencies

https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path

If the user is not packaging individually, then we can create one Lambda Layer with the python requirements, and the functions just use that layer, rather than having to have the packages in each function deployment.

If they are packaging individually, then maybe there's the option of specifying which ones are common and therefore can go into a layer. This will make the package and upload process faster, and also resulting lambda deployment package smaller (as they will share the layer)

whilst I write this I spotted a blog of someone else doing this:

https://nordcloud.com/lambda-layers-for-python-runtime/

so.. what you reckon?

**Comment by str3tch** [comment] 2018-12-05 06:38
serverless framework supports layers: https://serverless.com/blog/publish-aws-lambda-layers-serverless-framework/

**Comment by dschep** [comment] 2018-12-05 13:47
Duplicate of #295

**Closed by dschep** 2018-12-05 13:47 UTC
