### ISSUE TITLE
Error when trying to deploy

### ISSUE THREAD

**Issue by lucasventurasc** [UnitedIncome/serverless-python-requirements#140] opened 2018-02-23 11:24 UTC
Hi, I'm facing an error when I deploying my application using serverless-python-requirements

Error message:
Serverless plugin "serverless-python-requirements" initialization errored: Unexpected token {

Version:
"devDependencies": {
    "serverless-python-requirements": "^3.3.0"
  }

I'm using ${opt:vars} inside serverless.yml, that is the only difference that I found look for examples on the internet, I don't know if is a bug or I'm doing something wrong 

Thanks for attention

**Comment by dschep** [comment] 2018-02-23 13:33
dupe of #136. the plugin requires node 6. alas @npm only warns about it instead erroring out :(

**Closed by dschep** 2018-02-23 13:33 UTC
