### ISSUE TITLE
cannot build from multiple package paths

### ISSUE THREAD

**Issue by farridav** [UnitedIncome/serverless-python-requirements#224] opened 2018-08-02 19:20 UTC
When using `package > include` in serverless.yml, alongside `module: mymodule` the package rules are completely ignored, and only the module is packaged up.

I have made a repo to demonstrate this issue

https://github.com/farridav/sls_python

Hope this is enough information to reproduce the issue, shout if not

**Comment by farridav** [comment] 2018-08-02 19:26
Update: May be related to https://github.com/UnitedIncome/serverless-python-requirements/issues/168 and a whole bunch of other similar issues, though the linked repo might give more insight than other tickets..

**Comment by farridav** [comment] 2018-08-03 07:07
Also, I'm not sure why, but this module is causing sls deploy to use a different artefact, when the original one is exactly what i need, see:

```
sls package && find .serverless/ -name *.zip -exec unzip -l {} \;

Serverless: Adding Python requirements helper to functions/my_function...
Serverless: Installing requirements of functions/my_function/requirements.txt in .serverless/functions/my_function...
Serverless: Zipping required Python packages for functions/my_function...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Removing Python requirements helper from functions/my_function...
Serverless: Injecting required Python packages to package...
Archive:  .serverless/functions/my_function-sls-test-dev-my_function.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2098-01-01 00:00   requirements.txt
       22  2098-01-01 00:00   .requirements.zip
      119  2098-01-01 00:00   handler.py
       34  2098-01-01 00:00   other_file.py
      458  2098-01-01 00:00   unzip_requirements.py
---------                     -------
      633                     5 files
Archive:  .serverless/my_function.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       40  1980-01-01 00:00   functions/common/utils.py
       22  1980-01-01 00:00   functions/my_function/.requirements.zip
      119  1980-01-01 00:00   functions/my_function/handler.py
       34  1980-01-01 00:00   functions/my_function/other_file.py
        0  1980-01-01 00:00   functions/my_function/requirements.txt
      458  1980-01-01 00:00   functions/my_function/unzip_requirements.py
---------                     -------
      673                     6 files
```

The second of the two zip packages has everything i need in it, albeit inside an unnecessary functions folder

**Comment by dschep** [comment] 2018-08-08 19:00
You are correct that this is a duplicate of #168, as such I'm gonna close this issue, follow the earlier one for any changes (sorry, I'm not likely to get to that anytime soon as I don't use that feature of the plugin and am short on development free time)

**Closed by dschep** 2018-08-08 19:00 UTC
